networks:
  foodsense:
    driver: bridge

volumes:
  mssql-data:

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - foodsense
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${SA_PASSWORD}", "-Q", "SELECT 1", "-No"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  auth:
    build:
      context: .
      dockerfile: src/Services/Auth/Auth.API/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: ${AUTH_CONNECTION}
      JwtSettings__SecretKey: ${JWT_KEY}
    ports:
      - "5001:8080"
    networks:
      - foodsense
    depends_on:
      sql-server:
        condition: service_healthy

  inventory:
    build:
      context: .
      dockerfile: src/Services/Inventory/Inventory.API/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: ${INVENTORY_CONNECTION}
      JwtSettings__SecretKey: ${JWT_KEY}
      Azure__TranslatorKey: ${TRANSLATOR_KEY}
      Azure__TranslatorRegion: ${TRANSLATOR_REGION}
    ports:
      - "5002:8080"
    networks:
      - foodsense
    depends_on:
      sql-server:
        condition: service_healthy

  recipe:
    build:
      context: .
      dockerfile: src/Services/Recipe/Recipe.API/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: ${RECIPE_CONNECTION}
      JwtSettings__SecretKey: ${JWT_KEY}
      Edamam__AppId: ${EDAMAM_APPID}
      Edamam__AppKey: ${EDAMAM_APPKEY}
    ports:
      - "5003:8080"
    networks:
      - foodsense
    depends_on:
      sql-server:
        condition: service_healthy

  gateway:
    build:
      context: .
      dockerfile: src/Gateway/ApiGateway/Dockerfile
    environment:
      JwtSettings__SecretKey: ${JWT_KEY}
      ReverseProxy__Clusters__AuthAPICluster__Destinations__AuthAPIDestination__Address: http://auth:8080
      ReverseProxy__Clusters__InventoryAPICluster__Destinations__InventoryAPIDestination__Address: http://inventory:8080
      ReverseProxy__Clusters__RecipesAPICluster__Destinations__RecipesAPIDestination__Address: http://recipe:8080
    ports:
      - "5173:8080"
    networks:
      - foodsense
    depends_on:
      - auth
      - inventory
      - recipe

  frontend:
    build:
      context: src/Frontend/ReactWeb
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:5173/api
    ports:
      - "3000:80"
    networks:
      - foodsense
    depends_on:
      - gateway