name: Gateway CI 

on:
  pull_request: 
    branches: [ "dev", "prod" ]
    paths: [ 'src/Gateway/**' ]
  push:
    branches:
      - dev
      - prod
      - 'feature/**'
    paths: ['src/Gateway/**']

jobs:
  build-gateway:
    uses: ./.github/workflows/template-ci.yml
    with:
      service: 'gateway'
      project_path: 'src/Gateway/Gateway.sln'
      dockerfile: 'src/Gateway/ApiGateway/Dockerfile'
      push: ${{ github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/prod' }}
      run_tests: false