name: Inventory CI 

on:
  pull_request: 
    branches: [ "dev", "prod"]
    paths: [ 'src/Services/Inventory/**', 'src/Common/**' ]

  push:
    branches:
      - dev
      - prod
      - 'feature/**'
    paths: [ 'src/Services/Inventory/**', 'src/Common/**' ]


jobs:
  build-inventory:
    uses: ./.github/workflows/template-ci.yml
    with:
      service: 'inventory'
      project_path: 'src/Services/Inventory/Inventory.sln'
      dockerfile: 'src/Services/Inventory/Inventory.API/Dockerfile'
      push: ${{ github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/prod' }}